#!/usr/bin/perl -w

# 生成 usys.S
print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

# 下面列出所有的系统调用，必须和 kernel/syscall.h 里对应
entry("exit");
entry("wait");

entry("kill");
entry("exec");
entry("write"); 
entry("getpid");

entry("sleep");
entry("setpriority");
entry("getpinfo");


